-- ============================================================================
-- User Roles & RBAC Migration
-- ============================================================================
-- Implements Role-Based Access Control with custom JWT claims
-- IMPORTANT: Users CANNOT modify their own role - only admins can

-- ============================================================================
-- CUSTOM TYPES
-- ============================================================================

CREATE TYPE public.app_role AS ENUM ('user', 'admin');

-- ============================================================================
-- USER ROLES TABLE
-- ============================================================================

CREATE TABLE public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL DEFAULT 'user',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  UNIQUE (user_id)
);

COMMENT ON TABLE public.user_roles IS 'Application roles for each user. Only admins can modify.';

-- Index for fast lookups
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);

-- ============================================================================
-- ROW LEVEL SECURITY - VERY RESTRICTIVE
-- ============================================================================

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Users can view their own role (read-only)
CREATE POLICY "Users can view their own role"
  ON public.user_roles
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Only admins can view all roles
CREATE POLICY "Admins can view all roles"
  ON public.user_roles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
      AND ur.role = 'admin'
    )
  );

-- Only admins can insert new roles
CREATE POLICY "Admins can insert roles"
  ON public.user_roles
  FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
      AND ur.role = 'admin'
    )
  );

-- Only admins can update roles (and cannot demote themselves)
CREATE POLICY "Admins can update roles"
  ON public.user_roles
  FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
      AND ur.role = 'admin'
    )
  )
  WITH CHECK (
    -- Prevent admin from demoting themselves
    NOT (user_id = auth.uid() AND role != 'admin')
  );

-- Only admins can delete roles (except their own)
CREATE POLICY "Admins can delete roles except their own"
  ON public.user_roles
  FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_roles ur
      WHERE ur.user_id = auth.uid()
      AND ur.role = 'admin'
    )
    AND user_id != auth.uid()
  );

-- ============================================================================
-- AUTO-CREATE USER ROLE ON SIGNUP
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user');
  RETURN NEW;
END;
$$;

-- Trigger to auto-create role when user signs up
CREATE TRIGGER on_auth_user_created_role
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user_role();

-- ============================================================================
-- CUSTOM ACCESS TOKEN HOOK
-- ============================================================================
-- This function injects the user_role into the JWT claims
-- It's called by Supabase Auth before issuing a token

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  claims JSONB;
  user_role public.app_role;
BEGIN
  -- Fetch the user role from user_roles table
  SELECT role INTO user_role
  FROM public.user_roles
  WHERE user_id = (event->>'user_id')::UUID;

  claims := event->'claims';

  IF user_role IS NOT NULL THEN
    -- Set the user_role claim
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  ELSE
    -- Default to 'user' if no role found
    claims := jsonb_set(claims, '{user_role}', '"user"');
  END IF;

  -- Update the claims in the event
  event := jsonb_set(event, '{claims}', claims);

  RETURN event;
END;
$$;

-- ============================================================================
-- PERMISSIONS FOR AUTH HOOK
-- ============================================================================

-- Grant necessary permissions to supabase_auth_admin
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;

GRANT EXECUTE ON FUNCTION public.custom_access_token_hook TO supabase_auth_admin;

-- Revoke from regular users - they should NOT be able to call this
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook FROM authenticated, anon, public;

-- Grant read access to user_roles for the auth hook
GRANT SELECT ON TABLE public.user_roles TO supabase_auth_admin;

-- Ensure regular users can't bypass RLS via the service role
-- The RLS policies above already handle this

-- ============================================================================
-- HELPER FUNCTION: Check if current user is admin
-- ============================================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid()
    AND role = 'admin'
  );
$$;

-- ============================================================================
-- HELPER FUNCTION: Get current user role from JWT
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS public.app_role
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(
    (auth.jwt() ->> 'user_role')::public.app_role,
    'user'::public.app_role
  );
$$;

-- ============================================================================
-- UPDATE TRIGGERS
-- ============================================================================

CREATE TRIGGER update_user_roles_audit
  BEFORE UPDATE ON public.user_roles
  FOR EACH ROW
  EXECUTE FUNCTION update_audit_columns();

-- ============================================================================
-- UPDATE EXISTING RLS POLICIES TO USE ROLE
-- ============================================================================

-- Update image_sets policy to use the new role system
DROP POLICY IF EXISTS "Image sets can be managed by admins" ON image_sets;

CREATE POLICY "Image sets can be managed by admins"
  ON image_sets
  FOR ALL
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ============================================================================
-- NOTE: Enable the hook in Supabase Dashboard
-- ============================================================================
-- After running this migration, you need to enable the hook:
-- 1. Go to Supabase Dashboard > Authentication > Hooks
-- 2. Enable "Customize Access Token (JWT) Claims"
-- 3. Select the function: public.custom_access_token_hook
--
-- For local development, add to supabase/config.toml:
-- [auth.hook.custom_access_token]
-- enabled = true
-- uri = "pg-functions://postgres/public/custom_access_token_hook"
